fix: f-string expression part cannot include a backslash
f-string and string concat is redundant and `\n` causes issues on older versions of python (I'm getting this on Python 3.13.5).

```
Traceback (most recent call last):
  File "/root/.local/bin/chnvml", line 3, in <module>
    from caioh_nvml_gpu_control.__main__ import script_call
  File "/root/.local/pipx/venvs/caioh-nvml-gpu-control/lib/python3.11/site-packages/caioh_nvml_gpu_control/__main__.py", line 9, in <module>
    import nvml_gpu_control
  File "/root/.local/pipx/venvs/caioh-nvml-gpu-control/lib/python3.11/site-packages/caioh_nvml_gpu_control/nvml_gpu_control.py", line 3, in <module>
    import helper_functions as main_funcs
  File "/root/.local/pipx/venvs/caioh-nvml-gpu-control/lib/python3.11/site-packages/caioh_nvml_gpu_control/helper_functions.py", line 261
    log_helper(f'{"\n" + "\n".join(log_msg) + "\n"}')
                                                    ^
SyntaxError: f-string expression part cannot include a backslash
```